/**
 * TABLE SCHEMA
 * All primary keys are generated by the database, i.e. when inserting ID should be omitted!
 * read https://www.oracletutorial.com/oracle-basics/oracle-identity-column/ for more information
 * REQUIRES oracle 12c or greater
 */

CREATE TABLE state(
    state_id NUMBER(2) GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    name VARCHAR(27)
)
/
CREATE TABLE city(
    city_id NUMBER(4) GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    state_id NUMBER(2) REFERENCES state(state_id)
)
/

CREATE TABLE address(
    address_id NUMBER(6) GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    city_id NUMBER(4) REFERENCES city(city_id),
    pincode NUMBER(6)
)
/

CREATE TABLE item(
    item_id NUMBER(6) GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    name VARCHAR(16)
)
/

CREATE TABLE distributor(
    distributor_id NUMBER(6) GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    address_id NUMBER(6) REFERENCES address(address_id)
)
/

CREATE TABLE employee(
    employee_id NUMBER(6) GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    name VARCHAR(25),
    age NUMBER(3),
    address_id NUMBER(6) REFERENCES address(address_id),
    distributor_id NUMBER(6) REFERENCES distributor(distributor_id)
)
/

CREATE TABLE family(
    family_id NUMBER(6) GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    family_name VARCHAR(20),
    property NUMBER(2),
    annual_income NUMBER(10,2),
    distributor_id NUMBER(6) REFERENCES distributor(distributor_id),
    address_id NUMBER(6) REFERENCES address(address_id)
)
/

CREATE TABLE members(
    member_id NUMBER(6) GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    family_id NUMBER(6) REFERENCES family(family_id),
    name VARCHAR(25),
    age NUMBER(3)
)
/

CREATE TABLE inventory(
    inventory_id NUMBER(6) GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    distributor_id NUMBER(6) REFERENCES distributor(distributor_id),
    item_id NUMBER(6) REFERENCES item(item_id),
    amount NUMBER(5)
)
/

CREATE TABLE allocation(
    allocation_id NUMBER(6) GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    family_id NUMBER(6) REFERENCES family(family_id),
    item_id NUMBER(6) REFERENCES item(item_id),
    amount NUMBER(4),
    price NUMBER(6,2),
    allocation_date DATE
)
/

CREATE TABLE transaction(
    transaction_id NUMBER(6) GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    member_id NUMBER(6),
    allocation_id NUMBER(6),
    transaction_time TIMESTAMP,
    amount NUMBER(4),
    bill NUMBER(6,2)
)
/

CREATE TABLE admin(
    user_id NUMBER(6) GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    username VARCHAR(10),
    password VARCHAR(162)
)
/

CREATE TABLE family_user(
    user_id NUMBER(6) GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    family_id NUMBER(6) REFERENCES family(family_id),
    username VARCHAR(10),
    password VARCHAR(162)
)
/